# Build the bundled illustrative example dataset for IBMR.
#
# This is a SIMULATED example (not real GWAS data) constructed to mirror a
# realistic instrument-borrowing setting: a positive exposure -> primary-outcome
# effect, an auxiliary outcome that shares a subset of pleiotropic (invalid)
# instruments with the primary outcome, and strong instruments throughout so
# both IBPRESSO and IBMODE behave stably. Trait names (BMI, CAD, T2D) are used
# only to make the workflow concrete and easy to read.
#
# The raw values are generated by data-raw/gen_example.py (seed 2025) and stored
# in data-raw/sim_bmi_cad_t2d.csv. Run once from the package root:
#   Rscript data-raw/build_ibmr_example.R

d <- read.csv("data-raw/sim_bmi_cad_t2d.csv", stringsAsFactors = FALSE)

BetaYG_matrix   <- as.matrix(d[, c("Beta_CAD", "Beta_T2D")])
seBetaYG_matrix <- as.matrix(d[, c("se_CAD", "se_T2D")])
colnames(BetaYG_matrix)   <- c("Primary", "Auxiliary")
colnames(seBetaYG_matrix) <- c("Primary", "Auxiliary")
rownames(BetaYG_matrix)   <- d$SNP

dat_ibpresso_aux1 <- data.frame(
  SNP          = d$SNP,
  BetaOutcome  = d$Beta_CAD,   # primary outcome
  BetaExposure = d$BetaXG,     # exposure
  BetaAux      = d$Beta_T2D,   # auxiliary outcome
  SdOutcome    = d$se_CAD,
  SdExposure   = d$seBetaXG,
  SdAux        = d$se_T2D,
  stringsAsFactors = FALSE
)

ibmr_example <- list(
  BetaXG                = d$BetaXG,
  seBetaXG              = d$seBetaXG,
  BetaYG_matrix         = BetaYG_matrix,
  seBetaYG_matrix       = seBetaYG_matrix,
  primary_trait         = "Primary",
  candidate_auxiliaries = c("Auxiliary"),
  recommended_auxiliary = "Auxiliary",
  dat_ibpresso_aux1     = dat_ibpresso_aux1,
  source_note = paste(
    "Simulated illustrative example (not real GWAS data): one exposure,",
    "one primary outcome, and one auxiliary outcome;", nrow(d),
    "strong instruments with pleiotropy shared between the two outcomes."
  )
)

usethis::use_data(ibmr_example, overwrite = TRUE)
cat("Saved data/ibmr_example.rda with", nrow(d), "instruments\n")
